import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ChatProvider } from '@/context/chatContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  weights: [400, 500, 600, 700],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <ChatProvider>{children}</ChatProvider>
      </body>
    </html>
  );
}
